
package Axis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://example")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param temp
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sayHowAreYouFromReturn", targetNamespace = "http://example", partName = "sayHowAreYouFromReturn")
    public String sayHowAreYouFrom(
        @WebParam(name = "temp", targetNamespace = "http://example", partName = "temp")
        String temp);

    /**
     * 
     * @param hiWord
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sayHelloWorldFromReturn", targetNamespace = "http://example", partName = "sayHelloWorldFromReturn")
    public String sayHelloWorldFrom(
        @WebParam(name = "hiWord", targetNamespace = "http://example", partName = "hiWord")
        String hiWord);

}
