
package DcuServise;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Services", targetNamespace = "http://Server")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Services {


    /**
     * 
     * @param mInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getCurrentVersionReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "getCurrentVersion", targetNamespace = "http://Server", className = "DcuServise.GetCurrentVersion")
    @ResponseWrapper(localName = "getCurrentVersionResponse", targetNamespace = "http://Server", className = "DcuServise.GetCurrentVersionResponse")
    public String getCurrentVersion(
        @WebParam(name = "mInfo", targetNamespace = "http://Server")
        boolean mInfo);

    /**
     * 
     * @param username
     * @param password
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getActiveUserReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "getActiveUser", targetNamespace = "http://Server", className = "DcuServise.GetActiveUser")
    @ResponseWrapper(localName = "getActiveUserResponse", targetNamespace = "http://Server", className = "DcuServise.GetActiveUserResponse")
    public String getActiveUser(
        @WebParam(name = "ip", targetNamespace = "http://Server")
        String ip,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param password
     * @param info
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "saveSeriSerialChangeReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "saveSeriSerialChange", targetNamespace = "http://Server", className = "DcuServise.SaveSeriSerialChange")
    @ResponseWrapper(localName = "saveSeriSerialChangeResponse", targetNamespace = "http://Server", className = "DcuServise.SaveSeriSerialChangeResponse")
    public ReturnMessage saveSeriSerialChange(
        @WebParam(name = "info", targetNamespace = "http://Server")
        ChangeInfo info,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param password
     * @param info
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "saveImageChangeReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "saveImageChange", targetNamespace = "http://Server", className = "DcuServise.SaveImageChange")
    @ResponseWrapper(localName = "saveImageChangeResponse", targetNamespace = "http://Server", className = "DcuServise.SaveImageChangeResponse")
    public ReturnMessage saveImageChange(
        @WebParam(name = "info", targetNamespace = "http://Server")
        ChangeImageInfo info,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param shenasnameInfo
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "shenasnameConfirmReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "shenasnameConfirm", targetNamespace = "http://Server", className = "DcuServise.ShenasnameConfirm")
    @ResponseWrapper(localName = "shenasnameConfirmResponse", targetNamespace = "http://Server", className = "DcuServise.ShenasnameConfirmResponse")
    public ReturnMessage shenasnameConfirm(
        @WebParam(name = "shenasnameInfo", targetNamespace = "http://Server")
        ShenasnameInfo shenasnameInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param personNin
     * @param username
     * @param password
     * @return
     *     returns DcuServise.MarriagesInfo
     */
    @WebMethod
    @WebResult(name = "getPersonMarriagesReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "getPersonMarriages", targetNamespace = "http://Server", className = "DcuServise.GetPersonMarriages")
    @ResponseWrapper(localName = "getPersonMarriagesResponse", targetNamespace = "http://Server", className = "DcuServise.GetPersonMarriagesResponse")
    public MarriagesInfo getPersonMarriages(
        @WebParam(name = "personNin", targetNamespace = "http://Server")
        long personNin,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param wifeNin
     * @param husbandNin
     * @param password
     * @return
     *     returns DcuServise.MarriagesInfo
     */
    @WebMethod
    @WebResult(name = "getParentsMarriagesReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "getParentsMarriages", targetNamespace = "http://Server", className = "DcuServise.GetParentsMarriages")
    @ResponseWrapper(localName = "getParentsMarriagesResponse", targetNamespace = "http://Server", className = "DcuServise.GetParentsMarriagesResponse")
    public MarriagesInfo getParentsMarriages(
        @WebParam(name = "husbandNin", targetNamespace = "http://Server")
        long husbandNin,
        @WebParam(name = "wifeNin", targetNamespace = "http://Server")
        long wifeNin,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param personNin
     * @param username
     * @param password
     * @return
     *     returns DcuServise.DivorcesInfo
     */
    @WebMethod
    @WebResult(name = "getPersonDivorcesReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "getPersonDivorces", targetNamespace = "http://Server", className = "DcuServise.GetPersonDivorces")
    @ResponseWrapper(localName = "getPersonDivorcesResponse", targetNamespace = "http://Server", className = "DcuServise.GetPersonDivorcesResponse")
    public DivorcesInfo getPersonDivorces(
        @WebParam(name = "personNin", targetNamespace = "http://Server")
        long personNin,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param wifeNin
     * @param husbandNin
     * @param password
     * @return
     *     returns DcuServise.DivorcesInfo
     */
    @WebMethod
    @WebResult(name = "getParentsDivorcesReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "getParentsDivorces", targetNamespace = "http://Server", className = "DcuServise.GetParentsDivorces")
    @ResponseWrapper(localName = "getParentsDivorcesResponse", targetNamespace = "http://Server", className = "DcuServise.GetParentsDivorcesResponse")
    public DivorcesInfo getParentsDivorces(
        @WebParam(name = "husbandNin", targetNamespace = "http://Server")
        long husbandNin,
        @WebParam(name = "wifeNin", targetNamespace = "http://Server")
        long wifeNin,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param shenasnameInfo
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "finalConfirmedShenasnameReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "finalConfirmedShenasname", targetNamespace = "http://Server", className = "DcuServise.FinalConfirmedShenasname")
    @ResponseWrapper(localName = "finalConfirmedShenasnameResponse", targetNamespace = "http://Server", className = "DcuServise.FinalConfirmedShenasnameResponse")
    public ReturnMessage finalConfirmedShenasname(
        @WebParam(name = "shenasnameInfo", targetNamespace = "http://Server")
        ShenasnameInfo shenasnameInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param password
     * @param info
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "signinUserReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "signinUser", targetNamespace = "http://Server", className = "DcuServise.SigninUser")
    @ResponseWrapper(localName = "signinUserResponse", targetNamespace = "http://Server", className = "DcuServise.SigninUserResponse")
    public ReturnMessage signinUser(
        @WebParam(name = "info", targetNamespace = "http://Server")
        SigninInfo info,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param userId
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "signoutUserReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "signoutUser", targetNamespace = "http://Server", className = "DcuServise.SignoutUser")
    @ResponseWrapper(localName = "signoutUserResponse", targetNamespace = "http://Server", className = "DcuServise.SignoutUserResponse")
    public ReturnMessage signoutUser(
        @WebParam(name = "userId", targetNamespace = "http://Server")
        String userId,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param password
     * @param birthInfo
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "saveBirthReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "saveBirth", targetNamespace = "http://Server", className = "DcuServise.SaveBirth")
    @ResponseWrapper(localName = "saveBirthResponse", targetNamespace = "http://Server", className = "DcuServise.SaveBirthResponse")
    public ReturnMessage saveBirth(
        @WebParam(name = "birthInfo", targetNamespace = "http://Server")
        BirthInfo birthInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param sanadInfo
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "sanadConfirmReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "sanadConfirm", targetNamespace = "http://Server", className = "DcuServise.SanadConfirm")
    @ResponseWrapper(localName = "sanadConfirmResponse", targetNamespace = "http://Server", className = "DcuServise.SanadConfirmResponse")
    public ReturnMessage sanadConfirm(
        @WebParam(name = "sanadInfo", targetNamespace = "http://Server")
        SanadInfo sanadInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param deathInfo
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "saveDeathReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "saveDeath", targetNamespace = "http://Server", className = "DcuServise.SaveDeath")
    @ResponseWrapper(localName = "saveDeathResponse", targetNamespace = "http://Server", className = "DcuServise.SaveDeathResponse")
    public ReturnMessage saveDeath(
        @WebParam(name = "deathInfo", targetNamespace = "http://Server")
        DeathInfo deathInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param marriageInfo
     * @param username
     * @param husbandInfo
     * @param wifeInfo
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "saveMarriageReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "saveMarriage", targetNamespace = "http://Server", className = "DcuServise.SaveMarriage")
    @ResponseWrapper(localName = "saveMarriageResponse", targetNamespace = "http://Server", className = "DcuServise.SaveMarriageResponse")
    public ReturnMessage saveMarriage(
        @WebParam(name = "husbandInfo", targetNamespace = "http://Server")
        WifeInfo husbandInfo,
        @WebParam(name = "wifeInfo", targetNamespace = "http://Server")
        WifeInfo wifeInfo,
        @WebParam(name = "marriageInfo", targetNamespace = "http://Server")
        MarriageInfo marriageInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

    /**
     * 
     * @param username
     * @param husbandInfo
     * @param divorceInfo
     * @param wifeInfo
     * @param password
     * @return
     *     returns DcuServise.ReturnMessage
     */
    @WebMethod
    @WebResult(name = "saveDivorceReturn", targetNamespace = "http://Server")
    @RequestWrapper(localName = "saveDivorce", targetNamespace = "http://Server", className = "DcuServise.SaveDivorce")
    @ResponseWrapper(localName = "saveDivorceResponse", targetNamespace = "http://Server", className = "DcuServise.SaveDivorceResponse")
    public ReturnMessage saveDivorce(
        @WebParam(name = "husbandInfo", targetNamespace = "http://Server")
        WifeInfo husbandInfo,
        @WebParam(name = "wifeInfo", targetNamespace = "http://Server")
        WifeInfo wifeInfo,
        @WebParam(name = "divorceInfo", targetNamespace = "http://Server")
        DivorceInfo divorceInfo,
        @WebParam(name = "username", targetNamespace = "http://Server")
        String username,
        @WebParam(name = "password", targetNamespace = "http://Server")
        String password);

}
